---
title: "Final_Project_Paper"
Author: "Jeffrey Gilbert"
format: html
---


```{r}
#Load in Libraries
library(tidytext)
library(tidyverse)
library(readtext)
library(tm)
library(topicmodels)
library(widyr)
library(SnowballC)
library(DigitalMethodsData)
library(wordVectors)
library(magrittr)
library(dplyr)
library(ggplot2)
```

```{r}
#load in dataset
metadata <- read.csv("ForeignPolicyBulletinData/metadata.csv")

fp.metadata <- separate(metadata,
         col = date,
         into = c("year", "month", "day"),
          remove = FALSE)

fpmeta <- as.data.frame(fp.metadata)
fp_texts <- readtext(paste("ForeignPolicyBulletinData/txt/", "*.txt", sep=""))
fp_whole <- full_join(fpmeta, fp_texts, by = c("filename" = "doc_id")) %>% as_tibble() 

stop_words_custom <- stop_words %>% 
  add_row(word="foreign", lexicon="NA")%>%
  add_row(word="policy", lexicon="NA")%>%
  add_row(word="international", lexicon="NA")%>%
  add_row(word="york", lexicon="NA")%>%
  add_row(word="act", lexicon="NA")%>%
  add_row(word="bulletin", lexicon="NA")%>%
  add_row(word="3", lexicon="NA")%>%
  add_row(word="association", lexicon="NA")%>%
  add_row(word="class", lexicon="NA")%>%
  add_row(word="published", lexicon="NA")%>%
  add_row(word="2", lexicon="NA")%>%
  add_row(word="december", lexicon="NA")%>%
  add_row(word="march", lexicon="NA")%>%
  add_row(word="post", lexicon="NA")%>%
  add_row(word="vol", lexicon="NA")%>%
  add_row(word="membership", lexicon="NA")%>%
  add_row(word="incorporated", lexicon="NA")%>%
  add_row(word="weekly", lexicon="NA")%>%
  add_row(word="5", lexicon="NA")%>%
  add_row(word="1", lexicon="NA")%>%
  add_row(word="4", lexicon="NA")%>%
  add_row(word="22", lexicon="NA")%>%
  add_row(word="8", lexicon="NA")%>%
  add_row(word="6", lexicon="NA")%>%
  add_row(word="7", lexicon="NA")%>%
  add_row(word="ing", lexicon="NA")%>%
  add_row(word="de", lexicon="NA")%>%
  add_row(word="tion", lexicon="NA")%>%
  add_row(word="vera", lexicon="NA")%>%
  add_row(word="vou", lexicon="NA")%>%
  add_row(word="editor", lexicon="NA")%>%
  add_row(word="subscription", lexicon="NA")%>%
  add_row(word="page", lexicon="NA")%>%
  add_row(word="printed", lexicon="NA")%>%
  add_row(word="ment", lexicon="NA")%>%
  add_row(word="matter", lexicon="NA")%>%
  add_row(word="publications", lexicon="NA")%>%
  add_row(word="con", lexicon="NA")%>%
  add_row(word="street", lexicon="NA")

tidy_fp <- fp_whole %>%
  unnest_tokens(word, text) %>% 
  filter(str_detect(word, "[a-z']$")) %>% 
  anti_join(stop_words_custom)

tidy_fp <- tidy_fp %>% filter(!grepl('[0-9]', word))
```


```{r}
#country word count
tidy_fp_countries <- tidy_fp %>% 
  filter(word %in% c("brazil", "argentina", "germany", "britain", "japan", "mexico", "soviet", "russia", "america", "chile", "venezuela")) %>% 
  count(word, sort = TRUE)
 

tidy_fp_countries
```

```{r}
#topic model
tidy_fp_words <- tidy_fp %>% count(filename, word)

fp.dtm <- tidy_fp_words %>% 
  count(filename, word) %>% 
  cast_dtm(filename, word, n)

fp3.lda <- LDA(fp.dtm, k = 16, control = list(seed = 12345), method = "Gibbs", alpha = 0.5)
fp3.lda

fp3.topics <- tidy(fp3.lda, matrix = "beta")

fp3.top.terms <- fp3.topics %>%
  arrange(desc(beta)) %>% 
  group_by(topic) %>% slice(1:10)

fp3.top.terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  ggplot(aes(beta, term, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  scale_y_reordered()
```


```{r}
#word vectors
if (!require(wordVectors)) {
  if (!(require(devtools))) {
    install.packages("devtools")
  }
  devtools::install_github("bmschmidt/wordVectors")
}

if (!file.exists("txt")) prep_word2vec(origin="ForeignPolicyBulletinData", destination="txt", lowercase=T, bundle_ngrams=1)

if (!file.exists("corpus_vectors.bin")) {model = train_word2vec("txt","corpus_vectors.bin",vectors=200, threads=5, window=12, iter=5, negative_samples=0)} else model = read.vectors("corpus_vectors.bin")
```

```{r}
nearest_to(model,model[["argentina"]], 75)
```

```{r}
nearest_to(model,model[["solidarity"]], 75)
```

```{r}
nearest_to(model,model[["germany"]], 75)
```



